# Setup
title:               shenyaojin.github.io
tagline:             Shenyao's Github page
description:         shenyaojin.github.io
url:                 ""
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num" 
permalink:           /:categories/:title/

markdown: kramdown

# About/contact
author:
  name:              Shenyao Jin
  url:               http://shenyaojin.github.io
  email:             shenyaojin@mines.edu
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.2.0
google_analytics_id: #UA-XXXX-Y
