# Setup
title:               shenyaojin.github.io
tagline:             'GP, DS and PE'
description:         'Shenyao_Github_Page'
url:                 ""
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num" 
permalink:           pretty

markdown: kramdown

# About/contact
author:
  name:              Shenyao Jin
  url:               http://shenyaojin.github.io
  email:             shenyaojin@mines.edu
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
